### ISSUE TITLE
Error calling ECS tasks. AccessDeniedException due iam:PassRole action

### ISSUE THREAD

**Issue by apsergithub** [aws/serverless-application-model#2247] opened 2021-11-25 13:46 UTC
### Description:
I have created a Lambda funtion that execute a ECS tasks using run_task from boto3
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.run_task

The policy inside my template look like this:

```yaml
      Policies:
        - EcsRunTaskPolicy:
            TaskDefinition: sample-batch-job:*

```
### Observed result:

I get an AccessDeniedException

> "errorMessage": "An error occurred (AccessDeniedException) when calling the RunTask operation: User: arn:aws:sts::123456789:assumed-role/[role]/[function] is not authorized to perform: iam:PassRole on resource: arn:aws:iam::123456789:role/ecsTaskExecutionRole because no identity-based policy allows the iam:PassRole action"

### Expected result:

EcsRunTaskPolicy should be enough to execute a ECS task, otherwise some documentation should be added to the development guide.

I think that something like this must be added automatically with EcsRunTaskPolicy

```json
  {
            "Effect": "Allow",
            "Action": [
                "iam:PassRole"
            ],
            "Resource": [
                "arn:aws:iam::************:role/ecsTaskExecutionRole"
            ]
  }
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. If using SAM CLI, `sam --version`: 1.36.0
3. AWS region: eu-west-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by torresxb1** [comment] 2021-11-27 00:40
Hi @apsergithub, could you a sample template and handler, or steps to reproduce this?

**Comment by apsergithub** [comment] 2021-12-01 11:22
Template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ECSCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ecs_call/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Policies:
        - EcsRunTaskPolicy:
            TaskDefinition: sample-batch-job:*

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ECSCallFunction:
    Description: "ECS call Lambda Function ARN"
    Value: !GetAtt ECSCallFunction.Arn
  ECSCallFunctionIamRole:
    Description: "Implicit IAM Role created for ECS call function"
    Value: !GetAtt ECSCallFunctionRole.Arn
```

Handler

```
import json
import boto3

def lambda_handler(event,context):
  client = boto3.client('ecs')
  response = client.run_task(
    capacityProviderStrategy=[
        {
            'capacityProvider': 'FARGATE_SPOT'
        },
    ],

  cluster='foobar', 
  #launchType = 'FARGATE',
  taskDefinition='sample-batch-job:1',
  count = 1,
  platformVersion='LATEST',
  networkConfiguration={
        'awsvpcConfiguration': {
            'subnets': [
                'subnet-0933a9a24a0888df6',
                'subnet-013be239a14c81b3d',
                'subnet-0cb6036951ec13541'
            ],
            'assignPublicIp': 'ENABLED'
        }
    })
  return str(response)

```

**Comment by aslam-experion** [comment] 2022-01-12 15:55
Hi @apsergithub, you got any solution? I am facing the same issue!

**Comment by giovangonzalez** [comment] 2022-03-23 15:17
Hi there, no response about this?? I'm having exactly the same error message:
"User: arn:aws:sts::xxxxxxx:assumed-role/xxxxxx-healthMonitorFunctionRole-45I6JXN6ASER/xxxxx-maintenance is not authorized to perform: ecs:DescribeServices on resource: arn:aws:ecs:us-west-2:xxxxxx:service/xxxx-load-test/xxxx-chat-service because no identity-based policy allows the ecs:DescribeServices action"

**Comment by ssenchenko** [comment] 2023-11-03 20:03
it seems like there are a couple of different issues here.
1. The original issue with `PassRole`. `PassRole` is not granted neither to a resource nor to a service. It's granted to a user so that one can give user a specific role ie to run ECS tasks and then a user can pass it to an service they run. It's out of SAM reach and we are closing this issue. You can read more about `iam:PassRole` [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_passrole.html)
2. @giovangonzalez We don't currently provide `ecs:DescribeServices` permission. In fact `ecs:RunTask` is the only action item in [`EcsRunTaskPolicy`](https://github.com/ssenchenko/serverless-application-model/blob/dbd2837957e4077d0fddab9fe181d1f48e6818f4/samtranslator/policy_templates_data/policy_templates.json#L891). If you need `ecs:DescribeServices` please create a feature request discussion [here](https://github.com/aws/serverless-application-model/discussions) as we're closing this issue. I would've created this feature request for you, but we'd like to here more about the context, than in your current message, why you would like to have `ecs:DescribeServices`

**Closed by ssenchenko** 2023-11-03 20:03 UTC
Labels: area/policy-templates, stage/needs-investigation
