### ISSUE TITLE
Authorizers don't work with explicit ServerlessRestApi API resource

### ISSUE THREAD

**Issue by keetonian** [aws/serverless-application-model#1108] opened 2019-08-28 22:14 UTC
**Description:**

Authorizers (at least default auth) does not work as expected when `ServerlessRestApi` is used as the name for a Serverless::Api.

This requires a deeper dive into how using the name `ServerlessRestApi` can affect SAM features. This is the name SAM uses for the implicit API, but this should behave the same as any other name if a customer doesn't use the implicit API.

You can avoid this bug in the meantime by not using the `ServerlessRestApi` name.

**Steps to reproduce the issue:**
1. Check out https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_lambda_token_auth/template.yaml
2. Run `bin/sam-translate.py` on the file after changing `MyApi` to `ServerlessRestApi`
3. View transformed file

**Observed result:**
No auth is configured on paths

**Expected result:**
Auth should be configured on all of the paths.

**Comment by hawflau** [comment] 2021-02-23 23:32
When parsing the template, SAM inserts an implicit API regardless it is needed or not, and removes if it is determined not needed afterwards. If an explicit API with logical ID "ServerlessRestApi" is defined and has API event sources referenced to it, SAM adds the corresponding path to the implicit API. When it checks whether the implicit API should be removed, because of the paths added, it determines the implicit API should not be removed. As a result, the explicit API with the same logical ID is dropped. 

So, it's not only `Authorizers` not working with explicit API with logical ID "ServerlessRestApi", but also any properties defined under this explicit API resource. Note: HttpApi might have the same issue, not confirmed yet.

Potential fixes:
* Option 1: distinguish whether an API event source is referencing an explicit API with logical ID "ServerlessRestApi", then exclude it from being inserted into the implicit API
* Option 2: just leave "ServerlessRestApi" as a reserved logicalID, and make it clear in docs that it should not be used

Relevant code: https://github.com/aws/serverless-application-model/blob/aaa1d15feac47288650c0d7bf08f918c0b3deeb8/samtranslator/plugins/api/implicit_api_plugin.py#L49-L92

**Comment by aaythapa** [comment] 2022-11-18 23:11
Fixing this issue in SAM transform would break backwards compatibility. Issue was addressed in SAM CLI through [this PR](https://github.com/aws/aws-sam-cli/pull/2907) which will send warnings when a reserved logical id is used.

**Closed by aaythapa** 2022-11-18 23:11 UTC
Labels: type/bug
