### ISSUE TITLE
HttpApi Event should not support `AWS::Serverless::Api`

### ISSUE THREAD

**Issue by hawflau** [aws/serverless-application-model#2119] opened 2021-08-10 23:20 UTC
### Description:

In this [test template](https://github.com/aws/serverless-application-model/blob/develop/tests/translator/input/api_with_any_method_in_swagger.yaml), the two events defined in the the Serverless Function are of type HttpApi, but the referenced Api is a serverless rest api (`AWS::Serverless::Api`). Looks like the template can be transformed successfully. But is it supposed for a HttpApi event to support a Rest Api event source?

### Observed result:

[Transformed template](https://github.com/aws/serverless-application-model/blob/develop/tests/translator/output/api_with_any_method_in_swagger.json)

### Expected result:

This test template should be invalid.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by jfuss** [comment] 2021-09-22 03:43
In the opposite case (Event with `Api` but references an `AWS::Serverless::HttpApi`) will fail. I decided not to address this one too, since it does success today. I think we should fix it but not sold on just updating and causing existing customer stacks to start failing. We should maybe do a reach out, since this could impact customers if they are unaware.

**Comment by hawflau** [comment] 2021-10-04 18:11
Just one thing came up on my mind - while the transform produces a successful translation in this case, I wonder if subsequent deployment would actually succeed. We probably should verify that first

**Comment by hoffa** [comment] 2022-12-07 01:15
To reproduce:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: foo
      Handler: bar
      Runtime: python3.7
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-Api
        paths:
          /:
            any:
              x-amazon-apigateway-integration:
                httpMethod: ANY
                type: http_proxy
                uri: https://www.foo.com
                payloadFormatVersion: '1.0'
```

Deploy:

```
sam deploy --region us-west-2 --resolve-s3 --capabilities CAPABILITY_IAM --stack-name test-app --template template.yaml
```

**Comment by hoffa** [comment] 2022-12-09 01:50
Changing the behavior would be considered a breaking change. Since this hasn't received much traction and [the documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html#sam-function-httpapi-apiid) is quite clear, I'll close it as `wontfix`. We can revisit as necessary.

**Closed by hoffa** 2022-12-09 01:50 UTC
Labels: type/bug, breaking-change, area/resource/http-api
