### ISSUE TITLE
CodeURI and InlineCode is Serverless::Function doesn't throw error

### ISSUE THREAD

**Issue by aaythapa** [aws/serverless-application-model#2067] opened 2021-06-21 17:18 UTC
I made a Serverless::Function resource with both the CodeUri and InlineCode property set

```TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: abc
        Key: abc.zip
        Version: 45345345
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
      Handler: app.lambda_handler
      Runtime: python3.8
```

The transformation didn't throw an InvalidResourceException and just took the InlineCode in the transformed resource.

```
"Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "ZipFile": "def handler(event, context):\n  print(\"Hello, world!\")\n"
        },
        "Handler": "app.lambda_handler",
.....
```

However I believe there is supposed to an error thrown as implied by this piece of code

https://github.com/aws/serverless-application-model/blob/c39d0a09623ea5eb47231682e20c97b7468ac481/samtranslator/model/sam_resources.py#L662-L664

**Comment by jfuss** [comment] 2021-06-21 21:24
@aaythapa Sadly we cannot throw because this will break existing customers. The current behavior is we accept both but default to `InlineCode`.

**Comment by jfuss** [comment] 2021-06-21 21:26
Closing as this is working as intended and as described above, we cannot change behavior to fail due to breaking backwards compatibility.

**Closed by jfuss** 2021-06-21 21:26 UTC
Labels: wontfix
