### ISSUE TITLE
Unable to disable 'schedule' event through use of parameter

### ISSUE THREAD

**Issue by dgard1981** [aws/serverless-application-model#2482] opened 2022-08-31 15:59 UTC
## Description:

I have a function with a `schedule` event, but unless I explicitly specify `Enabled: false` the EventBridge rule that is created is enabled.

I can't be sure, but I suspect that SAM is interrupting the value returned by `!Ref` and other intrinsic functions as a string, and that anything other than an explicit Boolean `false` is being transformed to `State: Enabled` for CloudFormation.

## Steps to reproduce:

Using the template and function below, build and run the function locally.

```shell
foo@bar:~$ sam build -u
foo@bar:~$ sam deploy --parameter-overrides FunctionEnabled=false
```

<details>
  <summary>SAM template</summary>

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  FunctionEnabled:
    Description: Whether the Function is enabled (via the scheduled rule).
    Type: String
    AllowedValues: [ 'true', 'false' ]
  Schedule:
    Description: The schedule on which the Function runs.
    Type: String
    Default: cron(0 3 1 * ? *)

Conditions:
  EnableFunction: !Equals [ !Ref FunctionEnabled, 'true' ]

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.8
    Timeout: 1

Resources:
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Function}"
      RetentionInDays: 7
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/.
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Enabled: !Ref FunctionEnabled
            Schedule: !Ref Schedule
            RetryPolicy:
              MaximumEventAgeInSeconds: 100
              MaximumRetryAttempts: 3
```
</details>

<details>
  <summary>Lambda function</summary>

```python
def lambda_handler(event, context):
    return {
        'statusCode': 200,
        'body': 'OK'
    }
```
</details>

## Observed result:

<details>
  <summary>Full logs for <code class="notranslate">sam build -u --debug</code></summary>
  
```console
2022-08-31 16:50:08,211 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-08-31 16:50:08,212 | Using config file: samconfig.toml, config environment: default
2022-08-31 16:50:08,212 | Expand command line arguments to:
2022-08-31 16:50:08,212 | --template_file=/home/me/sam-test/template.yaml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-08-31 16:50:08,321 | 'build' command is called
2022-08-31 16:50:08,321 | Starting Build inside a container
2022-08-31 16:50:08,326 | Collected default values for parameters: {'Schedule': 'cron(0 3 1 * ? *)'}
2022-08-31 16:50:08,339 | There is no customer defined id or cdk path defined for resource FunctionLogGroup, so we will use the resource logical id as the resource id
2022-08-31 16:50:08,340 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
2022-08-31 16:50:08,341 | 0 stacks found in the template
2022-08-31 16:50:08,342 | Collected default values for parameters: {'Schedule': 'cron(0 3 1 * ? *)'}
2022-08-31 16:50:08,353 | There is no customer defined id or cdk path defined for resource FunctionLogGroup, so we will use the resource logical id as the resource id
2022-08-31 16:50:08,354 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
2022-08-31 16:50:08,354 | 2 resources found in the stack 
2022-08-31 16:50:08,354 | Found Serverless function with name='Function' and CodeUri='code/.'
2022-08-31 16:50:08,354 | --base-dir is not presented, adjusting uri code/. relative to /home/me/sam-test/template.yaml
2022-08-31 16:50:08,362 | Instantiating build definitions
2022-08-31 16:50:08,365 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, /home/me/sam-test/code, Zip, , c13a826a-ef02-441f-aebd-392f5fd78509, {}, {}, x86_64, []), Current: BuildDefinition(python3.8, /home/me/sam-test/code, Zip, , c3ed3125-5bc5-44f9-b0e1-b9600f8a4f0c, {}, {}, x86_64, []), Function: Function(function_id='Function', name='Function', functionname='Function', runtime='python3.8', memory=None, timeout=1, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/me/sam-test/code', environment=None, rolearn=None, layers=[], events={'ScheduleEvent': {'Type': 'Schedule', 'Properties': {'Enabled': 'FunctionEnabled', 'Schedule': 'cron(0 3 1 * ? *)', 'RetryPolicy': {'MaximumEventAgeInSeconds': 100, 'MaximumRetryAttempts': 3}}}}, metadata={'SamResourceId': 'Function'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-08-31 16:50:08,365 | Building codeuri: /home/me/sam-test/code runtime: python3.8 metadata: {} architecture: x86_64 functions: Function
2022-08-31 16:50:08,366 | Building to following folder /home/me/sam-test/.aws-sam/build/Function

Fetching public.ecr.aws/sam/build-python3.8:latest-x86_64 Docker container image......
2022-08-31 16:50:09,611 | Mounting /home/me/sam-test/code as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
requirements.txt file not found. Continuing the build without dependencies.
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:CopySource
Creating target folders at /tmp/samcli/artifacts
Copying directory metadata from source (/tmp/samcli/source) to destination (/tmp/samcli/artifacts)
Copying source file (/tmp/samcli/source/app.py) to destination (/tmp/samcli/artifacts/app.py)
PythonPipBuilder:CopySource succeeded
2022-08-31 16:50:10,148 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
2022-08-31 16:50:10,148 | Build inside container was successful. Copying artifacts from container to host
2022-08-31 16:50:10,455 | Copying from container: /tmp/samcli/artifacts/. -> /home/me/sam-test/.aws-sam/build/Function
2022-08-31 16:50:10,510 | Build inside container succeeded
2022-08-31 16:50:10,510 | There is no customer defined id or cdk path defined for resource FunctionLogGroup, so we will use the resource logical id as the resource id
2022-08-31 16:50:10,510 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
[*] Deploy: sam deploy --guided
```
</details>

<details>
  <summary>Full logs for <code class="notranslate">sam deploy --parameter-overrides FunctionEnabled=false --debug</code></summary>
  
```console
2022-08-31 16:50:23,266 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-08-31 16:50:23,267 | Using config file: samconfig.toml, config environment: default
2022-08-31 16:50:23,267 | Expand command line arguments to:
2022-08-31 16:50:23,267 | --template_file=/home/me/sam-test/.aws-sam/build/template.yaml --parameter_overrides={'FunctionEnabled': 'false'} --fail_on_empty_changeset --confirm_changeset --on_failure=ROLLBACK --stack_name=Test-Schedule-Disabled --s3_bucket=my-deploy-us-east-1 --s3_prefix=test-schedule-disabled --capabilities=['CAPABILITY_IAM'] 
2022-08-31 16:50:23,474 | Collected default values for parameters: {'Schedule': 'cron(0 3 1 * ? *)'}
2022-08-31 16:50:23,488 | There is no customer defined id or cdk path defined for resource FunctionLogGroup, so we will use the resource logical id as the resource id
2022-08-31 16:50:23,488 | Sam customer defined id is more priority than other IDs. Customer defined id for resource Function is Function
2022-08-31 16:50:23,489 | 0 stacks found in the template
2022-08-31 16:50:23,532 | There is no customer defined id or cdk path defined for resource FunctionLogGroup, so we will use the resource logical id as the resource id
2022-08-31 16:50:23,532 | Sam customer defined id is more priority than other IDs. Customer defined id for resource Function is Function
2022-08-31 16:50:23,532 | Sam customer defined id is more priority than other IDs. Customer defined id for resource FunctionLogGroup is FunctionLogGroup
2022-08-31 16:50:23,532 | Sam customer defined id is more priority than other IDs. Customer defined id for resource Function is Function
2022-08-31 16:50:24,622 | File with same data already exists at test-schedule-disabled/da7c97b42276d6d18396784863e4fab3, skipping upload

        Deploying with following values
        ===============================
        Stack name                   : Test-Schedule-Disabled
        Region                       : us-east-1
        Confirm changeset            : True
        Disable rollback             : False
        Deployment s3 bucket         : my-deploy-us-east-1
        Capabilities                 : ["CAPABILITY_IAM"]
        Parameter overrides          : {"FunctionEnabled": "false"}
        Signing Profiles             : {}

Initiating deployment
=====================
2022-08-31 16:50:24,649 | Collected default values for parameters: {'Schedule': 'cron(0 3 1 * ? *)'}
2022-08-31 16:50:24,661 | Sam customer defined id is more priority than other IDs. Customer defined id for resource FunctionLogGroup is FunctionLogGroup
2022-08-31 16:50:24,661 | Sam customer defined id is more priority than other IDs. Customer defined id for resource Function is Function
2022-08-31 16:50:24,661 | 0 stacks found in the template
2022-08-31 16:50:24,661 | Collected default values for parameters: {'Schedule': 'cron(0 3 1 * ? *)'}
2022-08-31 16:50:24,673 | Sam customer defined id is more priority than other IDs. Customer defined id for resource FunctionLogGroup is FunctionLogGroup
2022-08-31 16:50:24,674 | Sam customer defined id is more priority than other IDs. Customer defined id for resource Function is Function
2022-08-31 16:50:24,675 | 2 resources found in the stack 
Uploading to test-schedule-disabled/33b00070172f79c4d6dcb49cde2e506d.template  1458 / 1458  (100.00%)

Waiting for changeset to be created..
CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                     LogicalResourceId                             ResourceType                                  Replacement                                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                         FunctionLogGroup                              AWS::Logs::LogGroup                           N/A                                         
+ Add                                         FunctionRole                                  AWS::IAM::Role                                N/A                                         
+ Add                                         FunctionScheduleEventPermission               AWS::Lambda::Permission                       N/A                                         
+ Add                                         FunctionScheduleEvent                         AWS::Events::Rule                             N/A                                         
+ Add                                         Function                                      AWS::Lambda::Function                         N/A                                         
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:402307313821:changeSet/samcli-deploy1661961025/57323f2e-be06-4d85-af88-cf9c464cfc9e


Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]: y

2022-08-31 16:50:44 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 0.5 seconds)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                ResourceType                                  LogicalResourceId                             ResourceStatusReason                        
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_COMPLETE                               AWS::IAM::Role                                FunctionRole                                  -                                           
CREATE_IN_PROGRESS                            AWS::Lambda::Function                         Function                                      -                                           
CREATE_IN_PROGRESS                            AWS::Lambda::Function                         Function                                      Resource creation Initiated                 
CREATE_COMPLETE                               AWS::Lambda::Function                         Function                                      -                                           
CREATE_IN_PROGRESS                            AWS::Logs::LogGroup                           FunctionLogGroup                              -                                           
CREATE_IN_PROGRESS                            AWS::Events::Rule                             FunctionScheduleEvent                         -                                           
CREATE_IN_PROGRESS                            AWS::Events::Rule                             FunctionScheduleEvent                         Resource creation Initiated                 
CREATE_IN_PROGRESS                            AWS::Logs::LogGroup                           FunctionLogGroup                              Resource creation Initiated                 
CREATE_COMPLETE                               AWS::Logs::LogGroup                           FunctionLogGroup                              -                                           
CREATE_COMPLETE                               AWS::Events::Rule                             FunctionScheduleEvent                         -                                           
CREATE_IN_PROGRESS                            AWS::Lambda::Permission                       FunctionScheduleEventPermission               -                                           
CREATE_IN_PROGRESS                            AWS::Lambda::Permission                       FunctionScheduleEventPermission               Resource creation Initiated                 
CREATE_COMPLETE                               AWS::Lambda::Permission                       FunctionScheduleEventPermission               -                                           
CREATE_COMPLETE                               AWS::CloudFormation::Stack                    Test-Schedule-Disabled                     -                                           
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Successfully created/updated stack - Test-Schedule-Disabled in us-east-1
```
</details>

In this example, I am directly referencing a parameter called `FunctionEnabled` which has allowed values of `[ 'true', 'false' ]`, but either way the EventBridge rule that is created is enabled.

```yml
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/.
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Enabled: !Ref FunctionEnabled
            Schedule: !Ref Schedule
            RetryPolicy:
              MaximumEventAgeInSeconds: 100
              MaximumRetryAttempts: 3
      Role: !GetAtt FunctionRole.Arn
```

I have also attempted to set the value through use of a condition and `!If` function, but the issue remains.

```yml
Conditions:
  EnableFunction: !Equals [ !Ref FunctionEnabled, 'true' ]

...
          Properties:
            Enabled: !Ref FunctionEnabled
```

And I have also tried to use the `!Equals` and `!Condition` functions, but again the issue remains.

```yml
          Properties:
            Enabled: !Condition EnableFunction
```

```yml
          Properties:
            Enabled: !Equals [ !Ref FunctionEnabled, 'true' ]
```

## Expected result:

I expected to be able to disable an EventBridge rule created in this way through use of parameters, rather than having to explicitly define `false` in the template.

## Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 22.04
2. SAM CLI version: `sam --version`: 1.55.0
3. AWS region: us-east-1

**Comment by jfuss** [comment] 2022-08-31 16:54
@dgard1981 This stems from SAM not being able to resolve intrinsic functions (CloudFormation resolves these after SAM runs). You should be able to migrate to use `State`. It was added https://github.com/aws/serverless-application-model/pull/1666 and deployed (to my knowledge) but docs have not been updated yet. So instead of using `Enabled`, which SAM tries to interpret, `State` is passed directly to the underlying resources.

**Comment by jfuss** [comment] 2022-08-31 16:55
Also duplicate of https://github.com/aws/serverless-application-model/issues/1329

**Comment by dgard1981** [comment] 2022-09-01 09:40
Thanks @jfuss, that seems to work.

However, it has exposed another issue with SAM 😢

With the template now as below, if I were to deploy to AWS while overriding the parameter `ScheduleState`, and then re-deploy without overriding that parameter, the default is ignored and the previous override value is still used, resulting in the changeset saying there are no changes to deploy.

It is possible to explicitly override the value again with the default, but it's not obvious that this is required, and if it was part of a larger change would likely be missed.

```shell
foo@bar:~$ sam build -u
foo@bar:~$ sam deploy --parameter-overrides ScheduleState=ENABLED
# EventBridge rule is enabled.
foo@bar:~$ sam deploy
# EventBridge rule is still enabled, default value of ScheduleState is not used.
foo@bar:~$ sam deploy --parameter-overrides ScheduleState=DISABLED
# EventBridge rule is disabled.
```

<details>
  <summary>SAM template</summary>

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  Schedule:
    Description: The schedule on which the Function runs.
    Type: String
    Default: cron(0 3 1 * ? *)
  ScheduleState:
    Description: Whether the OrchestratorFunction is enabled.
    Type: String
    AllowedValues: [ ENABLED, DISABLED ]
    Default: DISABLED

Globals:
  Function:
    Architectures:
      - x86_64
    Handler: app.lambda_handler
    Runtime: python3.8
    Timeout: 1

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/.
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            State: !Ref ScheduleState
            Schedule: !Ref Schedule
            RetryPolicy:
              MaximumEventAgeInSeconds: 100
              MaximumRetryAttempts: 3
```
<details>

**Closed** 2022-09-01 09:41 UTC
Labels: area/event-source, type/duplicate
