### ISSUE TITLE
Template Validation

### ISSUE THREAD

**Issue by keetonian** [aws/serverless-application-model#675] opened 2018-11-21 18:28 UTC
**Description:**

The template validator was disabled in #549 to fix warnings that appeared after a new release. Template validation needs to be updated to catch more template errors and make sure the `sam validate` command in SAM CLI works as expected.

Note: we will not be re-enabling the JSON schema for validation. The schema was used more for linting rather than for actual validation. We would like to integrate better with cfn-lint or some other validation schema to make this feature work better.

**Comment by matteofigus** [comment] 2018-11-28 13:08
I personally am a bit concerned of SAM validation being in another repo, as we will need to take care, during any API change in the future, to change the code in two places rather than one (transformer, docs, and some of the tests here and validation and other tests in the other repo), but let's give it a try - we can change that later if we don't like it.

I think my preference would be to:
1) Add the linter as dependency here, remove any unused code (including the json schema) and keep all the tests to ensure all the functionality is behaving as expected. Merge only when all the tests would be green (for instance, adding any extra validation into the linter to ensure all the validation scenarios are handled).
2) When merged, remove the validation unit tests here and in case port them to the linter as another Pull Request(s).
3) Reintroduce the validation back to the pre-transform phase and in case re-iterate until stable (in case adding more validation rules to the linter).
4) Upgrade SAM cli to use the latest version of this module, so that validation will happen both on `sam validate` and on `sam local start-api`, for improved Developer Experience.

How does it sound? I could have a go with the first step when we reach an agreement.

**Comment by jfuss** [comment] 2022-03-01 21:44
This issue seems out of date from current thinking (which makes sense given how old this is). We are looking to improve our validation in SAM directly with jsonschema (https://github.com/aws/serverless-application-model/issues/1133). The solution is not designed but current thinking is to provide a way SAM can be validated when CFN runs (removing some errors that get reported as internal errors instead of validation). This can also improve other tools (AWS SAM CLI, cfn-lint, etc).

Closing this as it feels it is a duplicate of https://github.com/aws/serverless-application-model/issues/1133

**Closed by jfuss** 2022-03-01 21:44 UTC
Labels: type/feature, priority/2-important, area/validation, maintainer/need-response
