### ISSUE TITLE
Cannot add DefaultAuthorizer to API Gateway

### ISSUE THREAD

**Issue by tobi5775** [aws/serverless-application-model#2960] opened 2023-02-27 11:30 UTC
### Description
I cannot add a DefaultAuthorizer to the API Gateway via AWS SAM template.

### Steps to reproduce
Add `AWS::Serverless::Api` to `template.yaml` with `Authorizers` and `DefaultAuthorizer`.
```
AWSTemplateFormatVersion: 2010-09-09

Transform:
  - AWS::Serverless-2016-10-31
 
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  AuthorizerFunctionArn:
    Type: String
    Description: Arn of the AuthorizerFunction

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AWS Api Gateway
      Auth:
        DefaultAuthorizer: BasicAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !Ref AuthorizerFunctionArn
            Identity:
              Header: Authorization
              ValidationExpression: ^[Bb]earer [-0-9a-zA-z\.]*$
              ReauthorizeEvery: 0
```

### Observed result
No Authorizer is added to the API Gateway as you can see here:
<img width="1415" alt="Bildschirmfoto 2023-02-27 um 12 20 19" src="https://user-images.githubusercontent.com/50146675/221550726-2b5a61b4-2d27-4940-9100-ed85f2cd5049.png">

No Authorizer is added to method.
<img width="383" alt="Bildschirmfoto 2023-02-27 um 12 24 01" src="https://user-images.githubusercontent.com/50146675/221551500-86f1b5ca-98a0-496b-b956-d1bda53b4420.png">

`AuthorizerFunctionArn` is a valid Arn.
<img width="813" alt="Bildschirmfoto 2023-02-27 um 12 22 44" src="https://user-images.githubusercontent.com/50146675/221551220-8992819e-ab05-4ef6-b671-daa2a8ef7417.png">

### Expected result
API Gateway has an authorizer and all methods are using the default authorizer.
Is there something missing in my template or something else blocking the authorizer creation?

### Additional environment details

1. OS: MacOS 12.1
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: SAM CLI, version 1.74.0
3. AWS region: eu-central-1

**Comment by GavinZZ** [comment] 2023-02-27 19:16
Hi there, after some investigation, I cannot reproduce your error. With the following template (that's based off from your given template)
```
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  AuthorizerFunctionArn:
    Type: String
    Description: Arn of the AuthorizerFunction

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: AWS Api Gateway
      DefinitionBody:
        swagger: '2.0'
        info:
          title: Example
          version: '1'
        paths:
          /test:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunctionArn}/invocations"
      Auth:
        DefaultAuthorizer: BasicAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !Ref AuthorizerFunctionArn
            Identity:
              Header: Authorization
              ValidationExpression: ^[Bb]earer [-0-9a-zA-z\.]*$
              ReauthorizeEvery: 0
```
<img width="809" alt="Screen Shot 2023-02-27 at 11 08 00 AM" src="https://user-images.githubusercontent.com/28763956/221659102-fd6fc63a-bbce-429a-91fb-4c34398ddd64.png">
I was able to deploy the stack with authorizer. 

You can try toggling the flag [`FailedOnWarnings`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-failonwarnings) to True, which may give you some more insight.

**Comment by tobi5775** [comment] 2023-02-28 08:44
Unfortunately `FailOnWarnings` changes nothing.

Here is the fully template.yaml:

```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  settlementservice

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  ApiGatewayStageName:
    Type: String
    Description: Api Gateway Stage Name
  Region:
    Type: String
    Description: Region
    Default: eu-central-1
  AuthorizerFunctionArn:
    Type: String
    Description: Arn of the AuthorizerFunction

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AWS Api Gateway
      FailOnWarnings: true
      Auth:
        DefaultAuthorizer: BasicAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          BasicAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !Ref AuthorizerFunctionArn
            Identity:
              Header: Authorization
              ValidationExpression: ^[Bb]earer [-0-9a-zA-z\.]*$
              ReauthorizeEvery: 0
  
  #### Division ####
  getAllDivisionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/division/get-all.getAllDivisionsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP get method to get all divisions from DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SettlementTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SettlementTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref SettlementTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessRestApi
            Path: /divisions
            Method: GET

  getDivisionByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/division/get-by-id.getDivisionByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A HTTP get method to get one division by id from DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SettlementTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SettlementTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          TABLE_NAME: !Ref SettlementTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ServerlessRestApi
            Path: /divisions/{divisionId}
            Method: GET

  SettlementTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SettlementTableNew
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: parentId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: parentId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SettlementUserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: SettlementStatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

```

Is something blocking the Authorizer creation?

**Comment by tobi5775** [comment] 2023-02-28 08:59
I also tried to add the Authorizer to my lambda function but getting following error during deplyoment:
`Event with id [Api] is invalid. Unable to set Authorizer [BasicAuthorizer] on API method [get] for path [/divisions] because the related API does not define any Authorizers.`

This error makes sense because the Authorizer is not created.

**Comment by GavinZZ** [comment] 2023-02-28 21:02
Thanks for the response! I can confirm that I am able to reproduce this issue using the template you gave. Investigating why no authorizer is created.

**Comment by GavinZZ** [comment] 2023-02-28 22:17
@tobi5775 There are one issue I spotted in your template: Your template does not define `StageName`. It's a required property so make sure you define it like `StageName: !Ref ApiGatewayStageName`. However, this is not the reason authorizer is not created. 

It turns out that it's due to a conflicting SAM API logical id with our implicit api name. If you change your API logical id to anything other than `ServerlessRestApi`, it should solve your problem. Let me know if this works for you.

I'm looking into the code to see if there is any change we can make to prevent issues like this from happening.

**Comment by GavinZZ** [comment] 2023-03-01 00:35
https://github.com/aws/serverless-application-model/issues/1108 Relevent issue.

**Comment by GavinZZ** [comment] 2023-03-01 01:30
SAM CLI has already added a warning for this scenario when you use the name `ServerlessRestApi` in the template. However, there is an edge case that SAM CLI only adds warning if using `Transform: AWS::Serverless-2016-10-31`. (It doesn't recognize list format). I'm going to add a fix for this.

**Comment by tobi5775** [comment] 2023-03-01 16:39
Thank you very much for your support! It was exactly the name 'ServerlessRestApi' that caused the problem. Now it is working as expected!

**Closed** 2023-03-01 18:29 UTC
Labels: type/bug, stage/bug-repro
