### ISSUE TITLE
Missing `sam destroy` CLI option

### ISSUE THREAD

**Issue by xirkus** [aws/serverless-application-model#1915] opened 2021-02-07 20:19 UTC
### Describe your idea/feature/enhancement

SAM should be able to teardown resources it has deployed. In addition, deployments that fail should be automatically cleaned up. 

### Proposal

There should be a `destroy` subcommand. You may also want to add a `status` subcommand to see if the current deployment is incomplete/wedged which could inform an end user whether or not they need to run `destroy`.

Currently, there are two work-arounds:

1. Go to the AWS Console and delete the Cloudformation Stack. This is not ideal for iterative programming development.
2. Use the IntelliJ AWS Toolkit.

Things to consider:
[ ] The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details

Please look at `serverless destroy` as an example.

**Comment by jfuss** [comment] 2021-02-08 19:50
Duplicate of https://github.com/aws/aws-sam-cli/issues/2191

**Closed by jfuss** 2021-02-08 19:50 UTC
