### ISSUE TITLE
Proposal: Edge (boolean) on Function

### ISSUE THREAD

**Issue by timoschilling** [aws/serverless-application-model#1569] opened 2020-04-23 17:50 UTC
**Description:**

If you want to use `AWS::Serverless::Function` for an Lambda@edge, you need to configure a special `AssumeRolePolicyDocument` and an `AutoPublishAlias`. It would be more hany if you just say `Edge: true` on the lambda.

**Current example:**

```yaml
  DownloadRequestTokenFunctionProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishAlias: edge
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action:
              - sts:AssumeRole
      CodeUri: .
```

**Future example:**

```yaml
  DownloadRequestTokenFunctionProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Edge: true
      CodeUri: .
```

**Expected result:**

Both templates delivering the same result. `Edge: true` builds an `AssumeRolePolicyDocument` for `lambda` / `edgelambda` and sets `AutoPublishAlias` to `edge`.

**More possible use cases:**

SAM CLI cloud add validation based on it to warn for the use of layers, runtimes not supported by edge, to hight timeouts (> 30 sec)

**Comment by aprilmintacpineda** [comment] 2021-03-18 03:14
Is it currently possible to set all my functions as lambda edge? I can see that in cloudformation, I can do it, but I will have to set each function arn individually, so it's quite inconvenient...

**Comment by jfuss** [comment] 2022-03-29 16:35
Duplicate of #323

Closing

**Closed by jfuss** 2022-03-29 16:35 UTC
Labels: type/feature, maintainer/need-response
