### ISSUE TITLE
Policies ignored with Role attached

### ISSUE THREAD

**Issue by MatteoInfi** [aws/serverless-application-model#1652] opened 2020-07-12 11:13 UTC
**Description:**

Looks like if I attach a Role to a lambda function all the policies get ignored, now this kind of makes sense since only one Role can be attached to a resource, but since it is very annoying to recreate all the policies I have, it would be nice if there was a workaround. Unfortunately I am forced to use a role because of KMS key policy introducing a circular dependency...

**Steps to reproduce the issue:**

```
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bin
      Handler: myFunction
      Role: !GetAtt MyRole.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - LambdaInvokePolicy:
            FunctionName: !Ref MyOtherFunction
        - Statement:
            - Effect: Allow
              Action:
                - ecs:RegisterTaskDefinition
                - ecs:CreateService
                - ecs:DescribeContainerInstances
                - ec2:DescribeInstances
              Resource:
                - "*"
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref MyTopic
```

**Observed result:**

From the console the only permission I can see belong to the Role, the rest is ignored

**Expected result:**

Should get the policies also

**Comment by timoschilling** [comment] 2020-07-14 19:11
Following the docs you can’t use policies and role at the same time.

**Comment by MatteoInfi** [comment] 2020-07-15 00:23
Well, that makes sense, however is a bit of a pain to recreate all the role and policies.

**Comment by CoshUS** [comment] 2020-11-26 22:20
Closing as this is by design.
Feel free to reopen if there is further issue.

**Closed by CoshUS** 2020-11-26 22:20 UTC
