### ISSUE TITLE
Cannot pass Dynamic path to a nested application using !Sub or !Ref intrinsic functions

### ISSUE THREAD

**Issue by jay-patel-simformsolutions** [aws/serverless-application-model#3144] opened 2023-05-03 14:45 UTC
parent-application.yaml
```
ChildApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/child1-application.yaml
      Parameters:
        Env: !Ref Env
```
And consider we have child1-application.yaml and child2-application.yaml in the resource directory so a static location path `resource/child1-application.yaml` works fine but `!Sub resource/${Env}-applicaion.yaml` does not work where Env is a command-line argument that is passed child1. It gives an error that the applicationId is missing, but the same error does not occur when I use static  `resources/child1-application.yaml`

**Comment by awood45** [comment] 2023-05-03 20:53
I don't quite follow some of the explanation - can you perhaps give me a minimal set of reproducing steps for this?

**Comment by jay-patel-simformsolutions** [comment] 2023-05-04 04:59
Sure, Basically I want to create 2 stacks 1 is parent stack and the other one is child stack, I want the child stack to be dynamic. To be very specific the child stack contains database. Now I want that for each env a database is created with a different specification, for eg. the prd, stg, uat must have a aurora-postgresql instance and the dev, test, playground and other short living environments should have simple RDS with postgresql instance to reduce the cost.

Code level example:
Our folder tree is something like this:
parent-stack.yaml
resources/
     - some-nested-stack.yaml
     - some-nested-stack2.yaml
     - prd-database.yaml
     - stg-database.yaml
     - dev-database.yaml


parent-stack.yaml
```
.
.
.
DatabaseStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/prd-database.yaml
      Parameters:
        Env: !Ref Env
```

So the above code example works perfectly fine because it is a static path in the template.yaml file itself. But what I am trying to achieve is I take a command line argument and make the Location Property for DatabaseStack dynamic. For e.g.
parent-stack.yaml
```
Parameter:
    Env:
         Type: String
         Description: Specifies the Environment that we want to deploy

.
.
.
    DatabaseStack:
        Type: AWS::Serverless::Application
        Properties:
            Location: !Sub resources/${Env}-database.yaml
            Parameters:
                   Env: !Ref Env
```

This gives me an error that the ApplicationId is required, Where as a static path was working correctly

I hope this gives more clarity

**Comment by awood45** [comment] 2023-05-05 22:18
This seems to be a case where the language extensions capability should help - can you try it? Described here: https://github.com/aws/serverless-application-model/issues/2533

**Comment by awood45** [comment] 2023-05-08 23:41
I think one challenge with this though is that you're using a `!Sub` property where everything appears to be local - is it safe to say your local file structure handles all of this?

If you were referring to uploaded SAR applications this would make more sense, but this isn't really what `!Sub` is meant to be used for if not - you're mixing things that resolve at deployment time with things that resolve at build time.

What I'd recommend instead is different templates for each environment, or having your embedded application accept a parameter and do the appropriate configuration.

Let me know if that helps - otherwise I can add this as a feature request discussion.

**Comment by awood45** [comment] 2023-05-08 23:44
In fact, this seems to cover the same ground as https://github.com/aws/aws-sam-cli/issues/4767

**Comment by awood45** [comment] 2023-05-08 23:45
I'm going to close this and recommend adding a plus-one to the linked issue if you want to use this pattern. The failure is before we get to any SAM Transform steps, so you'd be making a feature request for SAM CLI to process some intrinsic functions directly. If you're actually using deployed SAR applications in some way and see this issue, feel free to reopen.

**Closed by awood45** 2023-05-08 23:45 UTC
Labels: blocked/more-info-needed, stage/needs-triage
