### ISSUE TITLE
Provisioned Concurrency is not applied

### ISSUE THREAD

**Issue by olifer** [aws/serverless-application-model#1298] opened 2019-12-05 15:00 UTC
**Description:**

Setting Provisioned Concurrency on AWS::Serverless::Function in a cloudformation does not change aws lambda configuration when deployed.

**Steps to reproduce the issue:**
1. Deploy a lambda with `ProvisionedConcurrencyConfig` property set
```yaml
XLambda:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 40
      MemorySize: !Ref MemorySize
      Runtime: dotnetcore2.1
      Role: !GetAtt XLambdaRole.Arn
      Handler: x::FunctionHandlerAsync
      Tracing: Active   
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 5
      DeploymentPreference:
        Type: !Ref DeploymentPreference
```
**Observed result:**
Check if the config has been applied: 
- Using aws console
![image](https://user-images.githubusercontent.com/1049092/70246446-11c72680-1778-11ea-8663-88db3f7a94f2.png)

- Using aws cli
```
aws lambda list-provisioned-concurrency-configs --function-name x-lambda
{
    "ProvisionedConcurrencyConfigs": []
}
```

**Expected result:**
`ProvisionedConcurrentExecutions` is added to `Provisioned Concurrency Config` on the lambda.

**Comment by mpvosseller** [comment] 2020-02-12 16:56
I'm seeing similar behavior as well. After some testing it appears to me that this bug depends on the use of `DeploymentPreference`. In general it seems that `ProvisionedConcurrentExecutions` can not be updated when using `DeploymentPreference`.

For example I'm observing the following behavior:

- If `DeploymentPreference` is not used (at stack creation time or in any subsequent stack updates) then `ProvisionedConcurrentExecutions` works (and its value be updated) as expected.

- If the stack is initially created with `DeploymentPreference` but without `ProvisionedConcurrencyConfig` and then you try to add `ProvisionedConcurrentExecutions` in a subsequent update it will not be added.

- If both `DeploymentPreference` and `ProvisionedConcurrencyConfig` are used at stack creation time then `ProvisionedConcurrentExecutions` will initially be set correctly. However if you later try to change the value of `ProvisionedConcurrentExecutions` in a stack update, the new value will not take affect.

**Comment by sriram-mv** [comment] 2021-04-12 04:30
I tried to reproduce this. I started with a Lambda Function that has a Deployment Preference, and Set Provisioned Concurrency to be 5, Deployed successfully.

First Deployment: Changed it to 15, Deployed successfully and concurrency updated to 15 as well.
Second Deployment: Reduced it to 3, Deployed successfully and concurrency updated to 3 as well. (Unreserved Concurrency is given back too, back to 997)

New Resource with Deployment Preference, but no ProvisionedConcurrencyConfig -> deployed successfully.
Updated Resource with Deployment Preference and ProvisionedConcurrencyConfig (1)-> deployed successfully.

Final Deployment: remove all provisioned concurrency, (Unreserved concurrency back to 1000)

I was not able to reproduce this, closing this issue. Please comment if this still the issue or if I'm missing something.

**Closed by sriram-mv** 2021-04-12 04:30 UTC
Labels: stage/bug-repro, type/bug
