### ISSUE TITLE
Feature Request: Allow support to disable default execute-api REST API endpoint

### ISSUE THREAD

**Issue by honeykakkar** [aws/serverless-application-model#1995] opened 2021-04-19 16:45 UTC
### Describe your idea/feature/enhancement

Given that CloudFormation resource [AWS::ApiGateway::RestApi][2] generated by [AWS::Serverless::Api][3] supports [DisableExecuteApiEndpoint][4] property which allows users to specify whether clients can invoke underlying API by using the default execute-api endpoint, if it makes sense, can we add support for a similar property in [AWS::Serverless::Api][3] as well?

### Proposal

Add support for a property in [AWS::Serverless::Api][3] which can be passed directly to the [DisableExecuteApiEndpoint][4] property of underlying [AWS::ApiGateway::RestApi][2] resource.

### Motivation

It will be helpful for customers who use custom domain names for REST APIs and want to ensure that all traffic to their API only goes through the custom domain name and not the default endpoint (which doesn't use TLS 1.2)

Things to consider:
The [SAM documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification.html) will need to be updated

### Additional Details
[Resources generated by AWS::Serverless::Api][5]

  [1]: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/what-is-sam.html
  [2]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
  [3]: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
  [4]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-disableexecuteapiendpoint
  [5]: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources-api.html

**Comment by jithenshriyan** [comment] 2021-04-28 12:40
Hi, I'd love to contribute! I took a look at the AWS documentation and got a better understanding of the feature request. 

When users have custom domains, I believe it's mapped to a property called `DomainName`.  I wrote this statement which essentially validates whether the user has a custom domain, and if so set this new property in the Serverless API to true, which then is passed to the `DISABLE_EXECUTE_API_ENDPOINT` on the ApiGateway.

```python
 if _DOMAIN_NAME:
            disable_execute_api_endpoint = {"disableExecuteApiEndpoint": true}
            else:
                disable_execute_api_endpoint = {"disableExecuteApiEndpoint": false}
```

A lot of the other code required to complete this feature has already been written, so great work! This includes:

The endpoint configuration: `_X_APIGW_ENDPOINT_CONFIG = "x-amazon-apigateway-endpoint-configuration"`
Mapping the properties together: `DISABLE_EXECUTE_API_ENDPOINT = "disableExecuteApiEndpoint"`
Configurating the property inside of the ApiGateway: 
```python
 servers_configurations = self._doc.get(self._SERVERS, [{}])
        for config in servers_configurations:
            endpoint_configuration = config.get(self._X_APIGW_ENDPOINT_CONFIG, dict())
            endpoint_configuration[DISABLE_EXECUTE_API_ENDPOINT] = disable_execute_api_endpoint
            config[self._X_APIGW_ENDPOINT_CONFIG] = endpoint_configuration

        self._doc[self._SERVERS] = servers_configurations`
```

Let me know if there's anything else. Thanks!

**Comment by jithenshriyan** [comment] 2021-04-28 12:41
Also, @jfuss if you're open to releasing this feature, do you think we could get a PR open? Thanks!

**Comment by bonybrown** [comment] 2021-05-04 23:39
Possibly a duplicate of #1978

**Comment by hoffa** [comment] 2021-05-20 03:24
Closing in favor of the earlier https://github.com/aws/serverless-application-model/issues/1978.

**Closed by hoffa** 2021-05-20 03:24 UTC
Labels: area/resource/api, type/feature
