### ISSUE TITLE
AWS::Serverless::Function DynamoDB event update not possible anymore

### ISSUE THREAD

**Issue by michaelwittig** [aws/serverless-application-model#2011] opened 2021-05-06 17:04 UTC
When updating the code of a `AWS::Serverless::Function` resource with a DynamoDB event I started to see the following error today created by the `AWS::Lambda::EventSourceMapping` resource that is generated by SAM:

```
Resource handler returned message: "The event source arn (" arn:aws:dynamodb:us-east-1:***:table/***/stream/2020-11-14T18:35:12.693 ") and function (" *** ") provided mapping already exists. Please update or delete the existing mapping with UUID 44052f3a-13bb-4e94-a8d7-f09728d9fca4 (Service: Lambda, Status Code: 409, Request ID: a3edc8c9-e640-4732-9185-d19405fcaa3a, Extended Request ID: null)" (RequestToken: da10660c-5654-3019-b1d2-5777646726b3, HandlerErrorCode: AlreadyExists)
```

**Comment by michaelwittig** [comment] 2021-05-17 13:10
I opened an AWS Support request (8348786781) to speed things up a little ...

**Comment by hoffa** [comment] 2021-05-18 00:27
Could you provide a template so that we can reproduce the issue?

**Comment by michaelwittig** [comment] 2021-05-18 06:22
```yaml
  FunctionDynamoDBWatcher:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: 'build/handler/dynamoDBWatcher'
      Handler: 'bundle.handler'
      Runtime: 'nodejs14.x'
      MemorySize: 1536
      Timeout: 300
      Role: !GetAtt 'RoleDynamoDBWatcher.Arn'
      Environment:
        Variables:
          STAGE: !Ref Stage
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      Events:
        TeamTable:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt 'TeamTable.StreamArn'
            StartingPosition: LATEST
            BatchSize: 16
        AlertTable:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt 'AlertTable.StreamArn'
            StartingPosition: LATEST
            BatchSize: 16
        EscalationTable:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt 'EscalationTable.StreamArn'
            StartingPosition: LATEST
            BatchSize: 16
        IntegrationTable:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt 'IntegrationTable.StreamArn'
            StartingPosition: LATEST
            BatchSize: 16
      Tracing: Active
```

**Comment by michaelwittig** [comment] 2021-05-18 11:43
similar issue #1320

**Comment by hoffa** [comment] 2021-05-18 17:29
Thanks. I did the following:

```bash
sam init --name sam-app --runtime nodejs14.x --dependency-manager npm --app-template hello-world
```

Replaced `template.yml` by:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: MyAttribute
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: MyAttribute
          AttributeType: S
      StreamSpecification:
        StreamViewType: KEYS_ONLY

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        MyTableEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MyTable.StreamArn
            StartingPosition: LATEST
```

And deployed:

```bash
sam build --use-container
sam deploy --guided
```

Changing `Handler` or code referenced by `CodeUri` deployed fine. However, changing `StartingPosition` to `TRIM_LATEST` I was able to reproduce the issue.

Is this what you're experiencing?

**Comment by michaelwittig** [comment] 2021-05-18 18:32
I haven't changed anything than the file referenced in `CodeUri`. It seems to b a bug in CloudFormation.

**Comment by hoffa** [comment] 2021-05-20 21:23
Are you still experiencing this issue?

Indeed this seems to be on the CloudFormation side. In this case, all updating `CodeUri` does is change the `AWS::Lambda::Function`'s `S3Key` in the resulting CloudFormation template.

**Comment by hoffa** [comment] 2021-05-21 00:05
I was able to reproduce the same issue with a pure CloudFormation template in https://github.com/aws/serverless-application-model/issues/1320#issuecomment-845558908. I'll close this ticket in favor of the older https://github.com/aws/serverless-application-model/issues/1320.

**Closed by hoffa** 2021-05-21 00:05 UTC
Labels: area/cloudformation, stage/bug-repro, type/bug
