### ISSUE TITLE
Circular dependency between resources

### ISSUE THREAD

**Issue by kokakerze** [aws/serverless-application-model#2099] opened 2021-07-19 23:10 UTC
### Description:
When defining AWS::Serverless::Function as a trigger of AWS::S3::Bucket, currently it is impossible to SAM predefined policies with restricred access.

so for example let's take a look at following template:

```
Resources:

  BlobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"


  ProcessBlobFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blobsprjct/
      Handler: processBlob.lambda_handler
      Runtime: python3.8
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"
        - AmazonRekognitionFullAccess
      Events:
        BlobsBucket:
          Type: S3
          Properties:
            Bucket: !Ref BlobsBucket
            Events: s3:ObjectCreated:*
```

This will fail with:
Error: Failed to create changeset for the stack: blob, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Circular dependency between resources: [ProcessBlobFunction, ProcessBlobFunctionBlobsBucketPermission, BlobsBucket]

All resources says to set BucketName - I've already have it, i'm also add permission (Not sure that its needed, cause Error stayed bigger for 1 point)

```
  AllowS3ToCallLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref ProcessBlobFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt BlobsBucket.Arn
```

And this will fail with:
Error: Failed to create changeset for the stack: blob, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Circular dependency between resources: [ProcessBlobFunction, ProcessBlobFunctionBlobsBucketPermission, AllowS3ToCallLambdaPermission, BlobsBucket]

I am stuck and cannot find a solution for a long time . Help me resolve it please.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. If using SAM CLI, `sam --version`:
3. AWS region:

`Add --debug flag to any SAM CLI commands you are running`

**Comment by sriram-mv** [comment] 2021-07-27 20:46
I deployed a stack with following.

```
Resources:

  BlobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"


  ProcessBlobFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blobsprjct/
      Handler: processBlob.lambda_handler
      Runtime: python3.8
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"
        - AmazonRekognitionFullAccess
      Events:
        BlobsBucket:
          Type: S3
          Properties:
            Bucket: !Ref BlobsBucket
            Events: s3:ObjectCreated:*
```

and did not see the changeset error. 

Is that your full template or a part of it?

**Comment by SamStephens** [comment] 2021-07-28 03:03
I've just encountered this. I suspect the original poster has accidentally posted their workaround, rather than the original code. It fails when you try and Ref the S3 bucket in the policy.

I would expect

```
Resources:

  BlobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"


  ProcessBlobFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: blobsprjct/
      Handler: processBlob.lambda_handler
      Runtime: python3.8
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BlobsBucket
        - AmazonRekognitionFullAccess
      Events:
        BlobsBucket:
          Type: S3
          Properties:
            Bucket: !Ref BlobsBucket
            Events: s3:ObjectCreated:*
```

To fail with a circular reference.

**Comment by sriram-mv** [comment] 2021-07-30 16:31
Ah, I see. this is a known issue AFAIK, will try to find to relevant issues.

**Comment by jfuss** [comment] 2021-08-05 15:11
There are a couple closed issues about this already (search for "Circular Dependency" and go to the closed issue tab).

So details inline here:

Some details you can read up on:
* https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/
* Circular dependency when specifying bucket reference in policy serverless-application-model#138
* https://stackoverflow.com/questions/50158593/work-around-circular-dependency-in-aws-cloudformation

The way I have typically solved this is by doing what @sriram-mv  or passing in a Parameter into the stack and control the name of buckets that way. If you go the Parameter route, you can `Ref` the Parameter for the bucket name anywhere you need. 

Closing as this is not actionable by SAM and the root cause being a limitation in CFN.

**Closed by jfuss** 2021-08-05 15:11 UTC
Labels: area/circular

**Comment by artsiomyemelyanenka** [comment] 2022-12-25 15:47
> I've just encountered this. I suspect the original poster has accidentally posted their workaround, rather than the original code. It fails when you try and Ref the S3 bucket in the policy.
> 
> I would expect
> 
> ```
> Resources:
> 
>   BlobsBucket:
>     Type: AWS::S3::Bucket
>     Properties:
>       BucketName: !Sub "blobs-${AWS::AccountId}-${AWS::Region}"
> 
> 
>   ProcessBlobFunction:
>     Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
>     Properties:
>       CodeUri: blobsprjct/
>       Handler: processBlob.lambda_handler
>       Runtime: python3.8
>       Policies:
>         - S3ReadPolicy:
>             BucketName: !Ref BlobsBucket
>         - AmazonRekognitionFullAccess
>       Events:
>         BlobsBucket:
>           Type: S3
>           Properties:
>             Bucket: !Ref BlobsBucket
>             Events: s3:ObjectCreated:*
> ```
> 
> To fail with a circular reference.

So apparently, it stopped working. I'm trying to figure out how to solve it in the current version.
