### ISSUE TITLE
sam incorrectly resolve parameters

### ISSUE THREAD

**Issue by mgorski-mg** [aws/serverless-application-model#1360] opened 2020-01-03 16:23 UTC
I have a problem to pass parameters to enable or disable Lambda Scheduler

Template:
```
Parameters:
  SchedulerCronParameter:
    Type: String
    Description: Enter scheduler cron expresion. Default is cron(0 1 1 * ? *).
    Default: cron(0 1 1 * ? *)
  SchedulerEnabledParameter:
    Type: String
    Description: Enable or disable scheduler. Default is true.
    Default: true
    AllowedValues: [true, false]

Resources:
  ScheduledLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Timeout: 900
      Tracing: Active
      Events:
        Schedule:
          Properties:
            Name: LambdaScheduler
            Description: Monthly schedule
            **Enabled: !Ref SchedulerEnabledParameter**
            Schedule: !Ref SchedulerCronParameter
            Input: '{"view_only": false}'
          Type: Schedule
```
I think it's because the template is translated before resolving CF Parameters.
Code from SAM translator:
```
if self.Enabled is not None:
            events_rule.State = "ENABLED" if self.Enabled else "DISABLED"
```

If the Parameter is not resolved before translation, it's always set State as 'ENABLED'.

Do you have any workaround for it?

SAM CLI version: 0.39.0

**Comment by mgorski-mg** [comment] 2020-01-03 21:47
@jfuss true that :sweat_smile: Thx!

**Comment by soccerboymalloy-patriot** [comment] 2020-06-19 17:05
Any updates or workarounds for this? We have a Lambda that we'd like to schedule in our Production account, but not in our Development account. We're trying to use TemplateConfiguration files in our CodePipeline in order to set this value. This bug is preventing us from disabling the schedule in our Development account.

I suppose we could define two Lambdas in our template (one with a schedule and one without) that get conditionally created based on the environment. But that's brittle, error prone, and ugly.

**Comment by mgorski-mg** [comment] 2020-06-19 21:02
> Any updates or workarounds for this? We have a Lambda that we'd like to schedule in our Production account, but not in our Development account. We're trying to use TemplateConfiguration files in our CodePipeline in order to set this value. This bug is preventing us from disabling the schedule in our Development account.
> 
> I suppose we could define two Lambdas in our template (one with a schedule and one without) that get conditionally created based on the environment. But that's brittle, error prone, and ugly.

You can define the scheduler using classic CloudFormation instead of the SAM.
You need to define `AWS::Events::Rule` and `AWS::Lambda::Permission`.
Than you can use parameters properly.

**Comment by soccerboymalloy-patriot** [comment] 2020-06-22 15:45
> You can define the scheduler using classic CloudFormation instead of the SAM.
> You need to define `AWS::Events::Rule` and `AWS::Lambda::Permission`.
> Then you can use parameters properly.

Thanks for the pointer! Sometimes I forget that I can mix and match CloudFormation and SAM. For reference, [this documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#aws-resource-events-rule--examples) is exactly what I needed.

**Comment by diegogurpegui** [comment] 2020-09-26 02:24
I just came across this issue.
Any update or progress? or the solution at the moment is still the one suggested by @mgorski-mg?

**Comment by RichieRunner** [comment] 2021-01-19 19:33
> 
> 
> I just came across this issue.
> Any update or progress? or the solution at the moment is still the one suggested by @mgorski-mg?

There's been no fix for this after 1 year, but there's a workaround discussed [here](https://github.com/aws/serverless-application-model/issues/1329)

**Comment by gghez** [comment] 2021-01-26 22:21
posted a workaround here: https://github.com/aws/serverless-application-model/issues/1329#issuecomment-767864926

**Comment by ckabalan** [comment] 2021-09-21 20:12
I just tried this today and it is still broken. The workaround by @mgorski-mg continues to work.

**Comment by Yop-La** [comment] 2022-04-26 15:00
The same on my side. The issue is still here.

**Comment by hoffa** [comment] 2022-10-17 21:48
You might be able to get this to work by adding [`AWS::LanguageExtensions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html) to `Transform` as such:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

`AWS::LanguageExtensions` [resolves intrinsic functions](https://aws.amazon.com/blogs/mt/introducing-new-language-extensions-in-aws-cloudformation/) if the value is known when `Transform`s are run.

See https://github.com/aws/serverless-application-model/issues/2533 for more information.

**Comment by hoffa** [comment] 2022-11-03 23:15
Closing in favor of https://github.com/aws/serverless-application-model/issues/2533.

**Closed by hoffa** 2022-11-03 23:15 UTC
Labels: type/feature, area/intrinsics, intrinsics/resolvable-predeployment
