### ISSUE TITLE
Secrets manager resolve for VPC endpoint ids in Rest API

### ISSUE THREAD

**Issue by sapessi** [aws/serverless-application-model#1600] opened 2020-05-26 20:25 UTC
**Description:**

We want to be able to configure API Gateway's private endpoint to create a private API. The VPC endpoint IDs are resolved through secrets manager. With CloudFormation, API Gateway supports two properties in [the `EndpointConfiguration` object](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html): `Type` and an array of `VpcEndpointIds`. With SAM, [the `EndpointConfiguration` property](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-endpointconfiguration) is a string and only supports the equivalent of the `Type` property in CloudFormation. Further, the template fails validation with SAM when we use the `{{resolve:ssm:...}}` syntax for the `EndpointConfiguration`.

**Steps to reproduce the issue:**
```yaml
EndpointConfiguration:
  Types: PRIVATE
  VpcEndpointIds=["{{resolve:ssm:vpcprivatelink-api_gateway-private_vpc_endpoint_id:1}}"]
```

**Observed result:**

**Expected result:**

**Comment by sriram-mv** [comment] 2020-05-27 23:01
A possible thing to do here so that there are backward incompatible changes is to introduce a new field called VpcEndpointIds as its own property under [AWS::Serverless::Api](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html) and only apply it if EndPointConfiuration is set to Private.

The value of VpcEndpointIds is now passed through to cloudformation as-is.

**Comment by mjdouble** [comment] 2020-05-28 14:56
Is this a duplicate of #1327 

Appears this PR will address it. #1524

**Comment by hoffa** [comment] 2022-12-07 03:31
As mentioned above, `VPCEndpointIds` already exist: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-endpointconfiguration.html#sam-api-endpointconfiguration-vpcendpointids

It's a pass-through property as well, so anything supported by regular CloudFormation will be supported by it.

**Closed by hoffa** 2022-12-07 03:31 UTC
Labels: area/troubleshooting, stage/accepted, maintainer/need-followup
