### ISSUE TITLE
Modifying sys.path at runtime can cause breaking changes in clients when package is upgraded

### ISSUE THREAD

**Issue by mjreid** [aws/serverless-application-model#2176] opened 2021-10-05 16:49 UTC
### Description:
Due to parts of this package containing code which modifies `sys.path`, adding modules can cause unexpected breaking changes when there are conflicting namespaces in client packages.

Specifically, my company encountered build failures when a package with a transitive dependency on aws-sam-translator (`moto==1.3.14`) automatically pulled in version 1.39.0 which was released on Sep 29, 2021. In our case, the issue was that we have an existing module named `metrics`, and in 1.39.0 [the metrics.py file](https://github.com/aws/serverless-application-model/blob/35ed6d01e0dbdd5fad2afe2b69d3e3751386a815/samtranslator/metrics/metrics.py) was added. Due to code in [feature_toggle.py](https://github.com/aws/serverless-application-model/blob/cc23278a97b6d482fbba310b5876071f13b15db8/samtranslator/feature_toggle/feature_toggle.py#L17) which modifies sys.path to include the parent directory as highest priority, the newly-added `metrics` module of aws-sam-translator took priority over our own module due to the import order.

### Steps to reproduce:

I realize importing `FeatureToggle` directly may not be common, but I'm doing this as a demonstration for a minimal reproduction.

Given this structure:
```
metrics/__init__.py
metrics/sample.py
main.py
```

`sample.py`:
```
class SomeClass:
    pass
```

`main.py`:
```
from samtranslator.feature_toggle.feature_toggle import FeatureToggle
from metrics.sample import SomeClass

if __name__ == "__main__":
    test = SomeClass()
    print("success")
```

### Observed result:
With `aws-sam-translator==1.39.0`:

```
Traceback (most recent call last):
  File "/xxx/sam-translator-test-case/main.py", line 2, in <module>
    from metrics.sample import SomeClass
ModuleNotFoundError: No module named 'metrics.sample'
```

### Expected result:
With `aws-sam-translator==1.38.0`:

```
success
```

**Comment by jfuss** [comment] 2021-10-11 20:58
Duplicate of https://github.com/aws/serverless-application-model/issues/1911

Closing

**Closed by jfuss** 2021-10-11 20:58 UTC
Labels: area/dependencies, stage/bug-repro
