### ISSUE TITLE
AWS::Serverless::Api AuthorizationScopes not being taken

### ISSUE THREAD

**Issue by pedrofurlanetto90** [aws/serverless-application-model#3325] opened 2023-08-28 14:09 UTC
### Description
`AWS::Serverless::Api` is not validating the JWT token scopes.

### Steps to reproduce

Configure the `AWS::Serverless::Api` Lambda authorizer with the following configuration and send a token without a scope or with a scope not present in the `AuthorizationScopes` list
```yaml
      Auth:
        Authorizers:
          LambdaAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: <lambda ARN>
            AuthorizationScopes:
            - a
            - b
            - c
            Identity:
              ValidationExpression: ^(Bearer )[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)$
```

### Observed result

The request is being routed to the Authorizer Lambda and lambda is trying to validate the token

### Expected result

The request should be blocked by API Gateway and lambda authorizer should not be called (same behavior when the token does not follow the regex configured in `ValidationExpression`)

### Additional environment details

1. OS:
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`:
3. AWS region: us-east-1

**Comment by GavinZZ** [comment] 2023-08-28 21:18
Hi @pedrofurlanetto90 thanks for raising an issue. I'll investigate it and keep you updated.

**Comment by GavinZZ** [comment] 2023-08-28 22:11
I noticed that there seems to be a error in our documentation. According to [AWS::ApiGateway::Method](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationscopes), this property `AuthorizationScopes` is only valid with cognito authorizer. 

I can confirm that this is true by using this template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          return {
            statusCode: 200,
            body: 'Success'
          }
        }
      Events:
        Auth:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Method: get
            Path: /auth
            Auth:
              Authorizer: MyLambdaTokenAuth

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuth
        Authorizers:
          MyLambdaTokenAuth:
            FunctionPayloadType: TOKEN
            AuthorizationScopes:
              - a
              - b
              - c
            FunctionArn:
              Fn::GetAtt: MyLambdaAuthFunction.Arn
            FunctionInvokeRole: !GetAtt LambdaAuthInvokeRole.Arn
            Identity:
              ValidationExpression: ^(Bearer )[a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)$

  LambdaAuthInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com

  MyLambdaAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      InlineCode: |
        exports.handler = async (event, context, callback) => {
          const token = event.type === 'TOKEN' ? event.authorizationToken : event.queryStringParameters.authorization
          const policyDocument = {
            Version: '2012-10-17',
            Statement: [{
              Action: 'execute-api:Invoke',
              Effect: token && token.toLowerCase() === 'allow' ? 'Allow' : 'Deny',
              Resource: event.methodArn
            }]
          }
          
          return {
            principalId: 'user',
            context: {},
            policyDocument
          }
        }
```
This template fails to deploy when I defined `AuthorizationScopes` while it works without this property.

I'm curious how did you deploy the template successfully with `AuthorizationScopes`?

**Comment by pedrofurlanetto90** [comment] 2023-08-29 01:17
@GavinZZ this is very weird. I just saw an error on my side when I forced an error by setting a single string for `AuthorizationScopes` value.
> Property 'Authorizers.LambdaAuthorizer.AuthorizationScopes' should be a list.

When I set a list for this property the deployment passes with success but the scope is not validated. Could it be related to the SAM CLI version? I'm using 1.50.0 version

**Comment by GavinZZ** [comment] 2023-08-29 16:25
@pedrofurlanetto90 Thanks for the response.

The first error message you mentioned `Property 'Authorizers.LambdaAuthorizer.AuthorizationScopes' should be a list.`, this is not a deployment error. It happens at changeset creation and this is expected because we validate the input and check if the type is a `list` type. 

I still cannot deploy with a list value for `AuthorizationScopes`. Can you provide a redacted template that I can use to deploy with a list `AuthorizationScopes` value and using an lambda `TOKEN` authorizer?

**Comment by GavinZZ** [comment] 2023-09-08 19:20
I have not heard back on this issue. Will proceed with documentation update on `AuthorizationScopes` property as it should only support Cognito Authorizers.

**Comment by ConnorRobertson** [comment] 2023-09-11 18:21
Closing for now, if you have any comments or questions please reopen!

**Closed by ConnorRobertson** 2023-09-11 18:21 UTC
Labels: type/bug, blocked/more-info-needed
