### ISSUE TITLE
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.

### ISSUE THREAD

**Issue by yeukfei02** [aws/serverless-application-model#1987] opened 2021-04-13 12:16 UTC
```
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:21
```

after I run `brew update` or `brew upgrade` or `brew cleanup` or `brew doctor`, it shows the above error.

where to fix this? or how to fix this?

thanks.

**Comment by jfuss** [comment] 2021-04-14 15:37
Moving to SAM CLI, as this is about the SAM CLI's Brew formula.

This is also a duplicate of https://github.com/aws/aws-sam-cli/issues/2803 so closing.

**Closed by jfuss** 2021-04-14 15:37 UTC
