### ISSUE TITLE
[Transform in CN-north-1 region] Failure when automatic IAM role is generated for Function in CN north region

### ISSUE THREAD

**Issue by keagansc2** [aws/serverless-application-model#1954] opened 2021-03-05 08:13 UTC
### Description:

When creating a serverless function within the CN-north-1 region following the (https://github.com/awslabs/aws-athena-hive-metastore ) the automation of delegating the "HiveMetastoreFunctionRole" resource will fail with the error:

Partition "aws" is not valid for resource "arn:aws:s3:::athena-hms-spill/*". (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 653affac-f52b-49f5-8de9-9fc6c19adb0d; Proxy: null)

This is due to the aws partition being selected and not aws-cn like all the other resources.

### Steps to reproduce:
Be within the cn-north-1 region and launch the lab.

### Observed result:
Failure from underlying IAM API as aws partition was chosen and not aws-cn

### Expected result:
Have the correct partition be selected.

**Comment by wchengru** [comment] 2021-03-11 05:09
Hi @keagansc2 , 
In order to detect the root cause of the issue, do you mind sharing the SAM template you are using? 
Please remove the sensitive user data from the template. We only need to know which resource your are using.

**Comment by keagansc2** [comment] 2021-03-11 06:28
Hi @wchengru ,

The SAM template is the identical one to the guide in the link provided for the "HiveMetastoreFunction":
https://github.com/awslabs/aws-athena-hive-metastore.

SAM template:
==================
```
Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdaFuncName:
    Description: The name you will give to this catalog in Athena will be used as the function name prefix.
    Type: String
  SpillLocation:
    Description: The S3 location where this function can spill metadata responses.
    Type: String
    Default: athena-hms-spill
  LambdaTimeout:
    Description: Maximum Lambda invocation runtime in seconds. (min 1 - 900 max)
    Default: 300
    Type: Number
  LambdaMemory:
    Description: Lambda memory in MB (min 128 - 3008 max).
    Default: 1024
    Type: Number
  HMSUris:
    Description: Hive metastore URIs
    Type: String
  VPCSubnetIds:
    Description: Comma separated VPC subnet IDs where hive metastore is in.
    Type: CommaDelimitedList
  VPCSecurityGroupIds:
    Description: Comma separated VPC security groups IDs where hive metastore is in.
    Type: CommaDelimitedList
Resources:
  HiveMetastoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          HMS_URIS:
            Ref: HMSUris
          SPILL_LOCATION:
            Fn::Sub: s3://${SpillLocation}
      FunctionName:
        Fn::Sub: ${LambdaFuncName}
      Handler: com.amazonaws.athena.hms.HiveMetaStoreLambdaFunc::handleRequest
      CodeUri:
        Bucket: bucket-in-cn-norht-cloned-from-hive
        Key: key-for-hive-github/s3
      Description: Allows Athena to call and execute queries with hive metastore.
      Runtime: java8
      Timeout:
        Ref: LambdaTimeout
      MemorySize:
        Ref: LambdaMemory
      Policies:
      - Statement:
        - Action:
          - lambda:GetFunction
          - lambda:InvokeFunction
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:GetObject
          - s3:GetBucketLocation
          - s3:ListBucket
          - s3:PutObject
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:s3:::${SpillLocation}/*
        Version: '2012-10-17'
      - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          Ref: VPCSecurityGroupIds
        SubnetIds:
          Ref: VPCSubnetIds
```

Reference Implementation for the SAM:
https://docs.aws.amazon.com/athena/latest/ug/datastores-hive-reference-implementation.html

**Comment by wchengru** [comment] 2021-03-11 06:37
Thanks @keagansc2 , that makes sense now! In this part:
```
          Resource:
            **Fn::Sub: arn:aws:s3:::${SpillLocation}/***
        Version: '2012-10-17'
      - VPCAccessPolicy: {}
      VpcConfig:
        SecurityGroupIds:
          Ref: VPCSecurityGroupIds
        SubnetIds:
          Ref: VPCSubnetIds
```
The resource is hard-coded to `arn:aws:s3:::${SpillLocation}/*`. That's the part you saw `arn:aws` instead of `arn:aws-cn`. Can you replace that part and have a try again?

**Comment by keagansc2** [comment] 2021-03-11 06:38
@wchengru ahhhhh ok thanks! Will attempt and let you know!

**Comment by wchengru** [comment] 2021-03-11 17:34
@keagansc2 I will close this issue. Please feel free to reopen it or create a new one if you have any questions, or issues.

**Closed by wchengru** 2021-03-11 17:34 UTC
Labels: type/question
